Lambda-ify enabling GuardDuty
turnerlabs/aws-guardduty-enterprise pull request #1
Opened 2018-10-10 18:07 UTC by nancytao

* Includes CloudFormation template to deploy stack 
* Lambda version is triggered by SNS and runs on a single account, specified by the SNS message
* Includes make targets to deploy, update, and test code

2018-10-12 13:45 UTC, jchrisfarris requested changes
This looks good. The only thing needing fixing is how gd_client is created on line 81

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +        return
This should also raise an error and cause the Lambda execution to error. return() ends up as a normal execution.

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +    role_arn = create_role_arn(event["payer_account_id"], os.environ["PAYER_ROLE"])
What you're doing here assume that the Payer Account is also the GuardDuty master account. This is not always the case. For us, we have a different payers and only one GuardDuty account. This Lambda should execute in the GuardDuty/Security Account.

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +    role_arn = create_role_arn(message['account_id'], os.environ['ASSUME_ROLE'])
Lets rename this to AUDIT_ROLE, and the other role as ACCEPT_ROLE

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +        aws_access_key_id=creds['AccessKeyId'],
Remove the creds, gd_client should be running against the GuardDuty Master which is what is executing this lambda.

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +            detector_id = create_parent_detector(gd_client, event, region)
If I had named this create_masteraccount_detector() it would have been less confusing

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +    account = describe_account(event)
This is where we get the root email for the target account. Good.

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +        accept_invite(account, os.environ['ASSUME_ROLE'], event, region)
So this is the ACCEPT_ROLE here.

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +        return(False)
We should raise an alert if we can't assume the role.

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +        return(False)
s/alert/exception/

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +    return f"arn:aws:iam::{account_id}:role/{role_name}"
TIL a better way to "some{}string".format()

2018-10-12 13:45 UTC, jchrisfarris commented on lambda/enable_guardduty.py
> +def describe_account(event):
If we called this from the handler vs process_region() the lambda might run marginally faster

2018-10-12 15:30 UTC, nancytao commented
* Changed `get_creds()` to raise an error if assume role fails, instead of at the call-site 
* Renamed PAYER_ROLE -> AUDIT_ROLE and ASSUME_ROLE -> ACCEPT_ROLE 
* Changed GuardDuty to run in the GuardDuty master instead of in payer account (and added those permissions to CloudFormation) 
* Small refactor to main handler, moved `describe_account()` to main handler

2018-12-05 13:51 UTC, jchrisfarris approved these changes

2018-12-05 13:52 UTC, merged